export const BODEGA_CREAR_FAIL = "BODEGA_CREAR_FAIL";
export const BODEGA_CREAR_REQUEST = "BODEGA_CREAR_REQUEST";
export const BODEGA_CREAR_SUCCESS = "BODEGA_CREAR_SUCCES";
export const BODEGA_CREAR_RESET = "BODEGA_CREAR_RESET";

export const GET_BODEGA_REQUEST = "GET_BODEGA_REQUEST";
export const GET_BODEGA_SUCCESS = "GET_BODEGA_EXITOSO";
export const GET_BODEGA_FAIL = "GET_BODEGA_FALLO";
