export const GET_COMENTARIOS_REQUEST = "GET_COMENTARIOS_REQUEST";
export const GET_COMENTARIOS_SUCCESS = "GET_COMENTARIOS_SUCCESS";
export const GET_COMENTARIOS_FAIL = "GET_COMENTARIOS_FAIL";
export const GET_COMENTARIOS_RESET = "GET_COMENTARIOS_RESET";

export const GET_ONECOMENTARIO_REQUEST = "GET_ONECOMENTARIO_REQUEST";
export const GET_ONECOMENTARIO_SUCCESS = "GET_ONECOMENTARIO_SUCCESS";
export const GET_ONECOMENTARIO_FAIL = "GET_ONECOMENTARIO_FAIL";
export const GET_ONECOMENTARIO_RESET = "GET_ONECOMENTARIO_RESET";

export const COMENTARIO_CREAR_REQUEST = "COMENTARIO_CREAR_REQUEST";
export const COMENTARIO_CREAR_SUCCESS = "COMENTARIO_CREAR_SUCCESS";
export const COMENTARIO_CREAR_FAIL = "COMENTARIO_CREAR_FAIL";
export const COMENTARIO_CREAR_RESET = "COMENTARIO_CREAR_RESET";

export const COMENTARIO_ACTUALIZAR_REQUEST = "COMENTARIO_ACTUALIZAR_REQUEST";
export const COMENTARIO_ACTUALIZAR_SUCCESS = "COMENTARIO_ACTUALIZAR_SUCCESS";
export const COMENTARIO_ACTUALIZAR_FAIL = "COMENTARIO_ACTUALIZAR_FAIL";
export const COMENTARIO_ACTUALIZAR_RESET = "COMENTARIO_ACTUALIZAR_RESET";

export const GET_TODOS_COMENTARIOS_REQUEST = "GET_TODOS_COMENTARIOS_REQUEST";
export const GET_TODOS_COMENTARIOS_SUCCESS = "GET_TODOS_COMENTARIOS_SUCCESS";
export const GET_TODOS_COMENTARIOS_FAIL = "GET_TODOS_COMENTARIOS_FAIL";
export const GET_TODOS_COMENTARIOS_RESET = "GET_TODOS_COMENTARIOS_RESET";

export const COMENTARIO_ELIMINAR_FAIL = "COMENTARIO_ELIMINAR_FAIL";
export const COMENTARIO_ELIMINAR_REQUEST = "COMENTARIO_ELIMINAR_REQUEST";
export const COMENTARIO_ELIMINAR_SUCCESS = "COMENTARIO_ELIMINAR_SUCCES";
export const COMENTARIO_ELIMINAR_RESET = "COMENTARIO_ELIMINAR_RESET";
