export const GET_NOVEDADES_REQUEST = "GET_NOVEDADES_REQUEST";
export const GET_NOVEDADES_SUCCESS = "GET_NOVEDADES_EXITOSO";
export const GET_NOVEDADES_FAIL = "GET_NOVEDADES_FALLO";

export const NOVEDAD_ELIMINAR_FAIL = "NOVEDAD_ELIMINAR_FAIL";
export const NOVEDAD_ELIMINAR_REQUEST = "NOVEDAD_ELIMINAR_REQUEST";
export const NOVEDAD_ELIMINAR_SUCCESS = "NOVEDAD_ELIMINAR_SUCCES";
export const NOVEDAD_ELIMINAR_RESET = "NOVEDAD_ELIMINAR_RESET";

export const NOVEDAD_CREAR_FAIL = "NOVEDAD_CREAR_FAIL";
export const NOVEDAD_CREAR_REQUEST = "NOVEDAD_CREAR_REQUEST";
export const NOVEDAD_CREAR_SUCCESS = "NOVEDAD_CREAR_SUCCES";
export const NOVEDAD_CREAR_RESET = "NOVEDAD_CREAR_RESET";
