export const OFERTA_CREAR_FAIL = "OFERTA_CREAR_FAIL";
export const OFERTA_CREAR_REQUEST = "OFERTA_CREAR_REQUEST";
export const OFERTA_CREAR_SUCCESS = "OFERTA_CREAR_SUCCES";
export const OFERTA_CREAR_RESET = "OFERTA_CREAR_RESET";

export const GET_OFERTAS_FAIL = "GET_OFERTAS_FAIL";
export const GET_OFERTAS_REQUEST = "GET_OFERTAS_REQUEST";
export const GET_OFERTAS_SUCCESS = "GET_OFERTAS_SUCCES";
export const GET_OFERTAS_RESET = "GET_OFERTAS_RESET";

export const GET_PRECIO_OFERTA_FAIL = "GET_PRECIO_OFERTA_FAIL";
export const GET_PRECIO_OFERTA_REQUEST = "GET_PRECIO_OFERTA_REQUEST";
export const GET_PRECIO_OFERTA_SUCCESS = "GET_PRECIO_OFERTA_SUCCES";
export const GET_PRECIO_OFERTA_RESET = "GET_PRECIO_OFERTA_RESET";

export const GET_GESTION_OFERTA_FAIL = "GET_GESTION_OFERTA_FAIL";
export const GET_GESTION_OFERTA_REQUEST = "GET_GESTION_OFERTA_REQUEST";
export const GET_GESTION_OFERTA_SUCCESS = "GET_GESTION_OFERTA_SUCCES";
export const GET_GESTION_OFERTA_RESET = "GET_GESTION_OFERTA_RESET";

export const ELMINIAR_OFERTA_FAIL = "ELMINIAR_OFERTA_FAIL";
export const ELMINIAR_OFERTA_REQUEST = "ELMINIAR_OFERTA_REQUEST";
export const ELMINIAR_OFERTA_SUCCESS = "ELMINIAR_OFERTA_SUCCES";
export const ELMINIAR_OFERTA_RESET = "ELMINIAR_OFERTA_RESET";
