export const GET_PRODUCTOS_REQUEST = "GET_PRODUCTOS_REQUEST";
export const GET_PRODUCTOS_EXITOSO = "GET_PRODUCTOS_EXITOSO";
export const GET_PRODUCTOS_FALLO = "GET_PRODUCTOS_FALLO";
export const GET_PRODUCTOS_RESET = "GET_PRODUCTOS_RESET";

export const GET_PRODUCTO_REQUEST = "GET_PRODUCTO_REQUEST";
export const GET_PRODUCTO_EXITOSO = "GET_PRODUCTO_EXITOSO";
export const GET_PRODUCTO_FALLO = "GET_PRODUCTO_FALLO";
export const GET_PRODUCTO_REINICIAR = "GET_PRODUCTO_REINICIAR";

export const PRODUCTO_CREAR_FAIL = "PRODUCTO_CREAR_FAIL";
export const PRODUCTO_CREAR_REQUEST = "PRODUCTO_CREAR_REQUEST";
export const PRODUCTO_CREAR_SUCCESS = "PRODUCTO_CREAR_SUCCES";
export const PRODUCTO_CREAR_RESET = "PRODUCTO_CREAR_RESET";

export const PRODUCTO_ACTUALIZAR__FAIL = "PRODUCTO_ACTUALIZAR_FAIL";
export const PRODUCTO_ACTUALIZAR_REQUEST = "PRODUCTO_ACTUALIZAR_REQUEST";
export const PRODUCTO_ACTUALIZAR_SUCCESS = "PRODUCTO_ACTUALIZAR_SUCCES";
export const PRODUCTO_ACTUALIZAR_RESET = "PRODUCTO_ACTUALIZAR_RESET";

export const PRODUCTO_ELIMINAR_FAIL = "PRODUCTO_ELIMINAR_FAIL";
export const PRODUCTO_ELIMINAR_REQUEST = "PRODUCTO_ELIMINAR_REQUEST";
export const PRODUCTO_ELIMINAR_SUCCESS = "PRODUCTO_ELIMINAR_SUCCES";
export const PRODUCTO_ELIMINAR_RESET = "PRODUCTO_ELIMINAR_RESET";
