export const GET_INGRESOS_BRUTOS_MES_REQUEST =
  "GET_INGRESOS_BRUTOS_MES_REQUEST";
export const GET_INGRESOS_BRUTOS_MES_SUCCESS =
  "GET_INGRESOS_BRUTOS_MES_SUCCESS";
export const GET_INGRESOS_BRUTOS_MES_FAIL = "GET_INGRESOS_BRUTOS_MES_FAIL";
export const GET_INGRESOS_BRUTOS_MES_RESET = "GET_INGRESOS_BRUTOS_MES_RESET";

export const GET_TIPO_MAS_VENDIDO_REQUEST = "GET_TIPO_MAS_VENDIDO_REQUEST";
export const GET_TIPO_MAS_VENDIDO_SUCCESS = "GET_TIPO_MAS_VENDIDO_SUCCESS";
export const GET_TIPO_MAS_VENDIDO_FAIL = "GET_TIPO_MAS_VENDIDO_FAIL";
export const GET_TIPO_MAS_VENDIDO_RESET = "GET_TIPO_MAS_VENDIDO_RESET";

export const GET_COMPORTAMIENTO_REQUEST = "GET_COMPORTAMIENTO_REQUEST";
export const GET_COMPORTAMIENTO_SUCCESS = "GET_COMPORTAMIENTO_SUCCESS";
export const GET_COMPORTAMIENTO_FAIL = "GET_COMPORTAMIENTO_FAIL";
export const GET_COMPORTAMIENTO_RESET = "GET_COMPORTAMIENTO_RESET";

export const GET_CANTIDAD_PRODUCTOS_MES_REQUEST =
  "GET_CANTIDAD_PRODUCTOS_MES_REQUEST";
export const GET_CANTIDAD_PRODUCTOS_MES_SUCCESS =
  "GET_CANTIDAD_PRODUCTOS_MES_SUCCESS";
export const GET_CANTIDAD_PRODUCTOS_MES_FAIL =
  "GET_CANTIDAD_PRODUCTOS_MES_FAIL";
export const GET_CANTIDAD_PRODUCTOS_MES_RESET =
  "GET_CANTIDAD_PRODUCTOS_MES_RESET";

export const GET_DATOS_VENTAS_REQUEST = "GET_DATOS_VENTAS_REQUEST";
export const GET_DATOS_VENTAS_SUCCESS = "GET_DATOS_VENTAS_SUCCESS";
export const GET_DATOS_VENTAS_FAIL = "GET_DATOS_VENTAS_FAIL";
export const GET_DATOS_VENTAS_RESET = "GET_DATOS_VENTAS_RESET";
