export const TIPOVINO_CREAR_FAIL = "TIPOVINO_CREAR_FAIL";
export const TIPOVINO_CREAR_REQUEST = "TIPOVINO_CREAR_REQUEST";
export const TIPOVINO_CREAR_SUCCESS = "TIPOVINO_CREAR_SUCCES";
export const TIPOVINO_CREAR_RESET = "TIPOVINO_CREAR_RESET";

export const GET_TIPOVINO_REQUEST = "GET_TIPOVINO_REQUEST";
export const GET_TIPOVINO_SUCCESS = "GET_TIPOVINO_EXITOSO";
export const GET_TIPOVINO_FAIL = "GET_TIPOVINO_FALLO";
