export const USUARIO_REGISTRAR_FAIL = "USUARIO_REGISTRAR_FAIL";
export const USUARIO_REGISTRAR_REQUEST = "USUARIO_REGISTRAR_REQUEST";
export const USUARIO_REGISTRAR_SUCCESS = "USUARIO_REGISTRAR_SUCCESS";

export const USUARIO_INICIARSESION_FAIL = "USUARIO_INICIARSESION_FAIL";
export const USUARIO_INICIARSESION_REQUEST = "USUARIO_INICIARSESION_REQUEST";
export const USUARIO_INICIARSESION_SUCCESS = "USUARIO_INICIARSESION_SUCCESS";

export const USUARIO_CERRARSESION = "USUARIO_CERRARSESION";

export const USUARIO_CERRAR_REQUEST = "USUARIO_CERRAR_REQUEST";
export const USUARIO_CERRAR_SUCCESS = "USUARIO_CERRAR_SUCCESS";
export const USUARIO_CERRAR_FAIL = "USUARIO_CERRAR_FAIL";
export const USUARIO_CERRAR_RESET = "USUARIO_CERRAR_RESET";

export const USUARIO_DETALLE_REQUEST = "USUARIO_DETALLE_REQUEST";
export const USUARIO_DETALLE_SUCCESS = "USUARIO_DETALLE_SUCCESS";
export const USUARIO_DETALLE_FAIL = "USUARIO_DETALLE_FAIL";
export const USUARIO_DETALLE_RESET = "USUARIO_DETALLE_RESET";

export const USUARIO_ACTUALIZAR_REQUEST = "USUARIO_ACTUALIZAR_REQUEST";
export const USUARIO_ACTUALIZAR_SUCCESS = "USUARIO_ACTUALIZAR_SUCCESS";
export const USUARIO_ACTUALIZAR_FAIL = "USUARIO_ACTUALIZAR_FAIL";
export const USUARIO_ACTUALIZAR_RESET = "USUARIO_ACTUALIZAR_RESET";
