export const VARIETAL_CREAR_FAIL = "VARIETAL_CREAR_FAIL";
export const VARIETAL_CREAR_REQUEST = "VARIETAL_CREAR_REQUEST";
export const VARIETAL_CREAR_SUCCESS = "VARIETAL_CREAR_SUCCES";
export const VARIETAL_CREAR_RESET = "VARIETAL_CREAR_RESET";

export const GET_VARIETAL_REQUEST = "GET_VARIETAL_REQUEST";
export const GET_VARIETAL_SUCCESS = "GET_VARIETAL_EXITOSO";
export const GET_VARIETAL_FAIL = "GET_VARIETAL_FALLO";
