export const VENTA_CREAR_REQUEST = "VENTA_CREAR_REQUEST";
export const VENTA_CREAR_SUCCESS = "VENTA_CREAR_SUCCESS";
export const VENTA_CREAR_FAIL = "VENTA_CREAR_FAIL";
export const VENTA_CREAR_RESET = "VENTA_CREAR_RESET";

export const GET_VENTAS_REQUEST = "GET_VENTAS_REQUEST";
export const GET_VENTAS_EXITOSO = "GET_VENTAS_EXITOSO";
export const GET_VENTAS_FALLO = "GET_VENTAS_FALLO";

export const GET_DETALLEVENTA_REQUEST = "GET_DETALLEVENTA_REQUEST";
export const GET_DETALLEVENTA_SUCCESS = "GET_DETALLEVENTA_SUCCESS";
export const GET_DETALLEVENTA_FAIL = "GET_DETALLEVENTA_FAIL";
export const GET_DETALLEVENTA_RESET = "GET_DETALLEVENTA_RESET";

export const GET_VENTA_REQUEST = "GET_VENTA_REQUEST";
export const GET_VENTA_SUCCESS = "GET_VENTA_SUCCESS";
export const GET_VENTA_FAIL = "GET_VENTA_FAIL";
export const GET_VENTA_RESET = "GET_VENTA_RESET";

export const VENTA_ENTREGAR_REQUEST = "VENTA_ENTREGAR_REQUEST";
export const VENTA_ENTREGAR_SUCCESS = "VENTA_ENTREGAR_SUCCESS";
export const VENTA_ENTREGAR_FAIL = "VENTA_ENTREGAR_FAIL";
export const VENTA_ENTREGAR_RESET = "VENTA_ENTREGAR_RESET";

export const VENTA_PAGAR_REQUEST = "VENTA_PAGAR_REQUEST";
export const VENTA_PAGAR_SUCCESS = "VENTA_PAGAR_SUCCESS";
export const VENTA_PAGAR_FAIL = "VENTA_PAGAR_FAIL";
export const VENTA_PAGAR_RESET = "VENTA_PAGAR_RESET";

export const VENTA_CANCELAR_REQUEST = "VENTA_CANCELAR_REQUEST";
export const VENTA_CANCELAR_SUCCESS = "VENTA_CANCELAR_SUCCESS";
export const VENTA_CANCELAR_FAIL = "VENTA_CANCELAR_FAIL";
export const VENTA_CANCELAR_RESET = "VENTA_CANCELAR_RESET";

export const VENTA_PAGAR_ENTREGAR_REQUEST = "VENTA_PAGAR_ENTREGAR_REQUEST";
export const VENTA_PAGAR_ENTREGAR_SUCCESS = "VENTA_PAGAR_ENTREGAR_SUCCESS";
export const VENTA_PAGAR_ENTREGAR_FAIL = "VENTA_PAGAR_ENTREGAR_FAIL";
export const VENTA_PAGAR_ENTREGAR_RESET = "VENTA_PAGAR_ENTREGAR_RESET";

export const GET_VENTAS_HOY_REQUEST = "GET_VENTAS_HOY_REQUEST";
export const GET_VENTAS_HOY_SUCCESS = "GET_VENTAS_HOY_SUCCESS";
export const GET_VENTAS_HOY_FAIL = "GET_VENTAS_HOY_FAIL";
export const GET_VENTAS_HOY_RESET = "GET_VENTAS_HOY_RESET";
